export const circleButtonStyle = {
    width: "50px",
    height: "50px",
    borderRadius: "50%",
    backgroundColor: "#593ea1",
    color: "white",
    fontSize: "24px",
    fontWeight: "bold",
    border: "none",
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    boxShadow: "0px 4px 6px rgba(0, 0, 0, 0.1)",
    position: "fixed",
    bottom: "20px",
    right: "20px",
    transition: "background-color 0.3s, transform 0.2s",
  };